hr_student/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls")),
]

myapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),  
    path('main/', views.main, name='main'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/edit_profile/', views.edit_profile, name='edit_profile'),
    path('accounts/edit_project/<int:pk>/', views.edit_project, name='edit_project'),  # URL для редактирования проекта
    path('accounts/delete_project/<int:pk>/', views.delete_project, name='delete_project'), 
    path('search_user/', views.search_user, name='search_user'),
    path('resume/<int:user_id>/', views.resume, name='resume'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Faculty(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=50)
    level = models.CharField(max_length=20)  

    def __str__(self):
        return self.name

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE, null=True)
    course = models.IntegerField(null=True)
    profile_photo = models.ImageField(upload_to='profile_photos/', null=True)  # Assuming you'll upload photos to a directory named 'profile_photos'
    github = models.URLField(null=True)
    languages = models.ManyToManyField(Language, through='StudentLanguage')  # Many-to-Many relationship with Language through StudentLanguage

    def __str__(self):
        return self.user.username
    
class StudentLanguage(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    proficiency_level = models.CharField(max_length=20)  # Proficiency level of the student in the language

    def __str__(self):
        return f"{self.student.user.username}'s {self.language.name} proficiency: {self.proficiency_level}"
    

class Project(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    photo = models.ImageField(upload_to='project_photos/')  # Папка для хранения фотографий проектов

    def __str__(self):
        return self.title

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Student, Faculty, StudentLanguage, Project

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            student = Student.objects.create(user=user)
            print("created")
        return user

class StudentLanguageForm(forms.ModelForm):
    class Meta:
        model = StudentLanguage
        fields = ('language', 'proficiency_level')

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('faculty', 'course', 'profile_photo', 'github')

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'description', 'photo')

myapp/views.py
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login
from django.shortcuts import get_object_or_404, render, redirect
from django.shortcuts import render, redirect,get_object_or_404
from django.urls import reverse_lazy
from .models import Project
from .forms import RegistrationForm, StudentLanguageForm, EditProfileForm, ProjectForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User



def index(request):
    return render(request, 'index.html')

@login_required
def profile(request):
    student = request.user.student
    projects = Project.objects.filter(student=student)
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.student = student
            project.save()
            return redirect('profile')  # Перенаправляем на страницу профиля после успешного добавления проекта
    else:
        form = ProjectForm()
    return render(request, 'accounts/profile.html', {'student': student, 'projects': projects, 'form': form})

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Registration successful. You can now log in.')
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

class CustomLoginView(LoginView):
    template_name = 'registration/login.html'  # Ваш шаблон для страницы входа
    redirect_authenticated_user = False  # Allow users to access the login page even if authenticated
    next_page = reverse_lazy('main')


@login_required
def edit_profile(request):
    student = request.user.student
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            return redirect('profile')  # Перенаправляем на страницу профиля после успешного сохранения
    else:
        form = EditProfileForm(instance=student)
    return render(request, 'accounts/edit_profile.html', {'form': form})


@login_required
def edit_project(request, pk):
    project = get_object_or_404(Project, id=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = ProjectForm(instance=project)
    return render(request, 'accounts/edit_project.html', {'form': form})

@login_required
def delete_project(request, pk):
    project = get_object_or_404(Project, id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('profile')
    return render(request, 'accounts/delete_project.html', {'project': project})



@login_required
def main(request):
    return render(request, 'main.html')



def search_user(request):
    users = User.objects.all()
    user_found = False

    if request.method == "POST":
        search = request.POST.get('search')
        searched_user = User.objects.filter(username__icontains=search).first()
        if searched_user:
            users = [searched_user]
            user_found = True

    return render(request, 'search_user.html', {'users': users, 'user_found': user_found})



def resume(request, user_id):
    user = get_object_or_404(User, id=user_id)
    projects = Project.objects.filter(student=user.student)  # Получаем проекты, связанные с пользователем
    return render(request, 'resume.html', {'user': user, 'projects': projects})

myapp/templates/accounts/delete_project.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Project</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
    <h2>Delete Project</h2>
    <p>Are you sure you want to delete "{{ project.title }}" project?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
    </form>
    </div>
</body>
</html>

myapp/templates/accounts/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h2>Edit Profile</h2>
        <form class="edit-profile-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_faculty">Faculty:</label>
                {{ form.faculty }}
            </div>
            <div class="form-group">
                <label for="id_course">Course:</label>
                {{ form.course }}
            </div>
            <div class="form-group">
                <label for="id_profile_photo">Profile Photo:</label>
                {{ form.profile_photo }}
            </div>
            <div class="form-group">
                <label for="id_github">Github:</label>
                {{ form.github }}
            </div>
            <button class="submit-button" type="submit">Save</button>
        </form>
    </div>
</body>
</html>

myapp/templates/accounts/edit_project.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Project</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
    <h2>Edit Project</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
    </div>
</body>
</html>

myapp/templates/accounts/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>
    <header>
        <div class="header-left">
            <span>{{ request.user.username }}</span>
            <button><a href="{% url 'search_user' %}">Search User</a></button>
            <button><a href="{% url 'profile' %}">Go to Profile</a></button>
        </div>
    </header>
        <div class="container">
            <h2>Student Profile</h2><br/>
            <div class="profile-details">
                <p>Name: {{ student.user.first_name }}</p>
                <p>Last Name: {{ student.user.last_name }}</p>
            
                <!-- Детали профиля студента -->
                <p>Faculty: {{ student.faculty }}</p>
                <p>Course: {{ student.course }}</p>
                {% if student.profile_photo %}
                <p>Profile Photo: <img src="{{ student.profile_photo.url }}" alt="Profile Photo"style="width: 150px; height: 150px;"></p>
                {% else %}
                <p>No profile photo available</p>
                {% endif %}
                <p>Github: <a href="{{ student.github }}">{{ student.github }}</a></p>
                <br/>
            
                <!-- Кнопка для перехода на страницу редактирования профиля -->
                <a href="{% url 'edit_profile' %}"><button>Edit Profile</button></a>
            
                <!-- Список проектов студента -->
            <br/><br/><br/><br/>
            <h3>Projects</h3>
                <ul>
                    {% for project in projects %}
                    <li>
                        <p>Title: {{ project.title }}</p>
                        <p>Description: {{ project.description }}</p>
                        {% if project.photo %}
                        <p>Photo: <img src="{{ project.photo.url }}" alt="Project Photo"></p>
                        {% endif %}
                        <p><a href="{% url 'edit_project' project.id %}">Edit</a> | <a href="{% url 'delete_project' project.id %}">Delete</a></p>
                    </li>
                    {% endfor %}
                </ul>
            
                <!-- Форма для добавления нового проекта -->
                <br/><br/>
                <h3>Add New Project</h3>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br/>
                    <button type="submit">Add Project</button>
                </form>
            </div>
        </div>

</body>
</html>

myapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>
        <div class="container">
            <h2>Welcome to HR ALMAU Project!</h2><br/>
            <p>Выберите действие:</p>
            <ul>
                <li><a href="{% url 'register' %}">Регистрация</a></li>
                <li><a href="{% url 'login' %}">Вход</a></li>
            </ul>
        </div>

</body>
</html>

myapp/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<style>
</style>
<body>
    <header>
        <div class="header-left">
            <span>{{ request.user.username }}</span>
            <button><a href="{% url 'search_user' %}">Search User</a></button>
            <button><a href="{% url 'profile' %}">Go to Profile</a></button>
        </div>
    </header>

    <h1>Welcome to the Main Page</h1>
</body>
</html>

myapp/templates/resume.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resume</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <div class="header-left">
            <span>{{ request.user.username }}</span>
            <button><a href="{% url 'search_user' %}">Search User</a></button>
            <button><a href="{% url 'profile' %}">Go to Profile</a></button>
        </div>
    </header>
    <div class="container">
        <h2>Student Profile</h2><br/>
        <div class="profile-details">
            <p>Name: {{ user.first_name }}</p>
            <p>Last Name: {{user.last_name }}</p>
        
            <!-- Детали профиля студента -->
            <p>Faculty: {{ user.student.faculty }}</p>
            <p>Course: {{ user.student.course }}</p>
            {% if user.student.profile_photo %}
            <p>Profile Photo: <img src="{{ user.student.profile_photo.url }}" alt="Profile Photo"style="width: 150px; height: 150px;"></p>
            {% else %}
            <p>No profile photo available</p>
            {% endif %}
            <p>Github: <a href="{{ user.student.github }}">{{ user.student.github }}</a></p>
            <br/>
        
        
        <br/><br/><br/><br/>
        <h3>Projects</h3>
            <ul>
                {% for project in projects %}
                <li>
                    <p>Title: {{ project.title }}</p>
                    <p>Description: {{ project.description }}</p>
                    {% if project.photo %}
                    <p>Photo: <img src="{{ project.photo.url }}" alt="Project Photo"></p>
                    {% endif %}
                    
                </li>
                {% endfor %}
            </ul>
        
          
        </div>
    </div>
    
</body>
</html>

myapp/templates/search_user.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search User</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <style>
        /* CSS for two-column layout */
        .container {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px; /* Adjust the gap between cards */
        }

        .profile-card {
            border: 1px solid #ccc;
            padding: 10px;
        }
    </style>
</head>
<body>
    <header>
        <div class="header-left">
            <span>{{ request.user.username }}</span>
            <button><a href="{% url 'search_user' %}">Search User</a></button>
            <button><a href="{% url 'profile' %}">Go to Profile</a></button>
        </div>
    </header>
    <h1>Search User</h1>
    <p><a href="{% url 'main' %}">Back to Main</a></p>
    <form id="searchForm" method="POST">
        {% csrf_token %}
        <input type="text" id="searchInput" name="search" placeholder="Enter username...">
        <button type="submit">Search</button>
    </form>

    <br>

    <div class="container">
        {% if users %}
            {% for user in users %}
                <div class="profile-card">
                    <h2><a href="/resume/{{ user.id }}/">{{ user.first_name }} {{ user.last_name }}</a></h2>
                    <div class="profile-details">
                        {% if user.student.profile_photo %}
                            <img src="{{ user.student.profile_photo.url }}" alt="Profile Photo" style="width: 100px; height: 100px;">
                        {% else %}
                            <p>No profile photo available</p>
                        {% endif %}
                        <p>Faculty: {{ user.student.faculty }}</p>
                        <p>Course: {{ user.student.course }}</p>
                        <p>Github: <a href="{{ user.student.github }}">{{ user.student.github }}</a></p>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</body>
</html>